### ISSUE TITLE
should == ignore the error values?

### ISSUE THREAD

**Issue by edzer** [Enchufa2/errors#13]
```r
> set_errors(1:3, .1) == set_errors(1:3, 0)
[1] TRUE TRUE TRUE
```
this might be a matter of dispute, but some of me says that the errors should be equal too for this answer.

**Comment by Enchufa2** [comment]
That's a very good question. I thought about it, but I didn't find consensus with myself... My programmer side says that two _objects_ are equal if their components are equal, one by one, including errors in this case. From the physics side, it's not that easy though. Suppose we weigh two different apples. If one is 100(1) g and the other 100(5) g, are they equal or different? What about 100(1) g vs. 100(1) g?

This is kind of a philosophical problem. Including the errors means that we are comparing measurement accuracy **and** precision, while not including them means that we are comparing accuracies only.

I don't have a strong opinion about this. What do you think would be more intuitive for the user?

**Comment by Enchufa2** [comment]
Oh, and an extra ball: if `set_errors(1, .1) == set_errors(1, 0)` is `FALSE`, what about `set_errors(1, .1) > set_errors(1, 0)`?

**Comment by edzer** [comment]
If we think of error-aware data as the means and standard deviations of normally distributed random variables (the assumption `errors` makes), the pdfs need to be identical for equality, not just the means. In case of `a > b`, the answer should be a `numeric` with the probability of `a` being larger than `b`, not a `logical`.

[This](http://nvlpubs.nist.gov/nistpubs/TechnicalNotes/NIST.TN.1943.pdf) report contains pointers to other systems that do calculus with uncertain data. R pkg `distr` gives
```r
> Norm(0,1) < Norm(0, .5)
Error in Norm(0, 1) < Norm(0, 0.5) : 
  comparison (3) is possible only for atomic and list types
> Norm(0,1) == Norm(0, .5)
Error in Norm(0, 1) == Norm(0, 0.5) : 
  comparison (1) is possible only for atomic and list types
```

**Comment by Enchufa2** [comment]
Given this precedent, maybe the best approach is to raise an informative error. The good thing of it is that you force the user to think about what they want to compare and do it explicitly (for example, using `as.numeric` to compare the value).
