### ISSUE TITLE
Exponentiation operator throws errors

### ISSUE THREAD

**Issue by johnblommers** [Enchufa2/errors#2]
Consider the following code:

```
var = -2.1
errors(var)=0.1
var^2
Error in if (digits < 0L) digits <- 6L else { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In log(.v(e1)) : NaNs produced
```

The obvious workaround is to use var*var to perform the squaring. Are you able to fix this problem?

```
var*var
4.4 +/- 0.3
```

**Comment by Enchufa2** [comment]
Thanks for the report, solved now.

Please, also note that `var*var` is not the same as `var^2` (see [this article](https://www.enchufa2.es/archives/x-x-is-not-2x.html)).

**Comment by johnblommers** [comment]
Excellent! I installed the updated package directly from your github repository and can confirm that exponentiation works correctly.

And thanks for the tip that `var^2` is not the same as `var*var`. This it turns out is easy to prove and it's a useful lesson in numerical analysis. `var*var` has less error.
