### ISSUE TITLE
Subtracting two numbers generates NaN and Inf values

### ISSUE THREAD

**Issue by johnblommers** [Enchufa2/errors#3]
Consider this code:

```
> library(errors)
> options(errors.notation = "plus-minus")
> x = 10
> y = 10
> errors(x)=1
> errors(y)=1
> x-y
(NaN +/- Inf)e-Inf
> 
```

**(NaN +/- Inf)e-Inf** isn't the result I would expect. I'd expect the correct value to be 0 +/- 1.41.

What do you think?

Update: the error occurs also by simply typing  `x-10` 

```

**Comment by Enchufa2** [comment]
Indeed, you are right. There could potentially be a significant number of special cases like this. Thanks, I'll take a look.

**Comment by nutterb** [comment]
I suspect there may be some unanticipated behavior in `propagate`. I was looking at it late last week, and was wondering if it was propagating errors over scalars correctly. I'll put together another example when I get to work. If I'm right (it happens sometimes ), I may have a fix to propose.

**Comment by Enchufa2** [comment]
BTW, look at this:

```r
x <- set_errors(10, 1)
y <- x - x
as.numeric(y)
#> [1] 0
errors(y)
#> [1] 1.414214
y
#> NaN(Inf)e-Inf
```

Therefore, the error is in `format.errors()`, not in `propagate()`.

**Comment by Enchufa2** [comment]
[This](https://github.com/Enchufa2/errors/commit/4bcb0e71406a3352a2a507b31a6bb1fc98dc8b6c#diff-cbb7235afee10c3646161358a7655b0aL3) was the error.

**Comment by nutterb** [comment]
Sorry for the spurious path. I was having trouble with `*.errors` last week, and after a cursory glance today I immediately realized that I had not transcribed your code correctly in my local testing (I had been using `errors(e1) * .v(e1)` instead of `errors(e1) * .v(e2)`).  I'll quietly go back to my corner now.

**Comment by johnblommers** [comment]
Excellent. I've re-installed `errors` from the repository and confirm the bug is eradicated.
